batch_size: 64
no_cuda: False
seed: 42
epochs: 10  #
classes: 2
threshold: 0.4

defaults:
  - _self_
  - dataset: benchmark
  - loss: huber  #

#------------------------- Hydra Config ------------------------#
hydra:
  job:
    name: CV  #
  run:
    dir: outputs_CV/${hydra.job.name}/${now:%Y-%m-%d_%H-%M}
  sweep:
    dir: multirun_CV/${hydra.job.name}/${now:%Y-%m-%d_%H-%M}
    subdir: ${hydra.job.override_dirname}
