_target_: src.dataset.rgbt_dataset
batch_size: ${batch_size}
topo: False
use_list: True
ext: png
data_path: 'data/ovaskainen23'
train_root: 'train'
val_root: 'valid'
test_root: 'test'
in_channels: 3
out_channels: 1
shape: 256